name: SimpleJail
main: com.imjake9.simplejail.SimpleJail
description: Very basic Jail plugin.
version: 1.7
author: imjake9
softdepend: [Vault]

commands:
  jail:
    description: Places a player in Jail.
    usage: |
           /<command> <player> [player2] ... [time] [reason]
  unjail:
    description: Removes a player from Jail.
    usage: |
           /<command> <player>
  setjail:
    description: Sets the Jail point.
    usage: |
           /<command>
           /<command> <x> <y> <z> <world>
  setunjail:
    description: Sets the Jail removal point.
    usage: |
           /<command>
           /<command> <x> <y> <z> <world>
  jailstatus:
    description: Checks remaining tempjail time.
    usage: |
           /<command>
           /<command> <player>

permissions:
  SimpleJail.jailstatus:
    description: Gives access to the jailtime command.
    default: true
  SimpleJail.*:
    description: Gives access to all SimpleJail commands.
    children:
      SimpleJail.jail: true
      SimpleJail.unjail: true
      SimpleJail.setjail: true
      SimpleJail.jailstatus: true