name: KarmicJail
main: com.mitsugaru.karmicjail.KarmicJail
description: Jail plugin for Mine-RP
version: 0.1
author: Original - imjake9 ... Fork - Mitsugaru
softdepend: [Vault]

commands:
  jail:
    description: Places a player in Jail.
    usage: |
           /<command> <player> [player2] ... [time] [reason]
  j:
    description: Places a player in Jail. Alias to jail.
    usage: |
           /<command> <player> [player2] ... [time] [reason]
  unjail:
    description: Removes a player from Jail.
    usage: |
           /<command> <player>
  setjail:
    description: Sets the Jail point.
    usage: |
           /<command>
           /<command> <x> <y> <z> <world>
  setunjail:
    description: Sets the Jail removal point.
    usage: |
           /<command>
           /<command> <x> <y> <z> <world>
  jailstatus:
    description: Checks remaining tempjail time.
    usage: |
           /<command>
           /<command> <player>
  jstatus:
    description: Checks remaining tempjail time. Alias to jailstatus.
    usage: |
           /<command>
           /<command> <player>
  jaillist:
    description: List jailed players.
    usage: |
           /<command>
  jlist:
    description: List jailed players. Alias to jaillist.
    usage: |
           /<command>
  jailversion:
    description: Get plugin version and config info.
    usage: |
           /<command>
  jversion:
    description: Get plugin version and config info. Alias to jailversion.
    usage: |
           /<command>

permissions:
  KarmicJail.jail:
    description: Ability to jail players.
    default: op
  KarmicJail.unjail:
    description: Ability to unjail players.
    default: op
  KarmicJail.setjail:
    description: Ability to set jail warp points.
    default: op
  KarmicJail.list:
    description: List players in jail
    default: op
  KarmicJail.jailstatus:
    description: Gives access to the jailtime command.
    default: true
  KarmicJail.*:
    description: Gives access to all KarmicJail commands.
    children:
      KarmicJail.jail: true
      KarmicJail.unjail: true
      KarmicJail.setjail: true
      KarmicJail.jailstatus: true
      KarmicJail.list: true