name: KarmicJail
main: com.mitsugaru.karmicjail.KarmicJail
description: Jail plugin for Mine-RP
version: 0.435
author: Original - imjake9 ... Fork - Mitsugaru
depend: [Vault]

commands:
  jail:
    description: Places a player in Jail.
    usage: |
           /<command> <player> [player2] ... [time] [reason]
  j:
    description: Places a player in Jail. Alias to jail.
    usage: |
           /<command> <player> [player2] ... [time] [reason]
  unjail:
    description: Removes a player from Jail.
    usage: |
           /<command> <player>
  setjail:
    description: Sets the Jail point.
    usage: |
           /<command>
           /<command> <x> <y> <z> <world>
  setunjail:
    description: Sets the Jail removal point.
    usage: |
           /<command>
           /<command> <x> <y> <z> <world>
  jailstatus:
    description: Checks remaining tempjail time.
    usage: |
           /<command>
           /<command> <player>
  jstatus:
    description: Checks remaining tempjail time. Alias to jailstatus.
    usage: |
           /<command>
           /<command> <player>
  jailhelp:
    description: Jail help.
    usage: |
           /<command>
  jhelp:
    description: Jail help. Alias to jailhelp.
    usage: |
           /<command>
  jaillist:
    description: List jailed players.
    usage: |
           /<command> [page]
  jlist:
    description: List jailed players. Alias to jaillist.
    usage: |
           /<command> [page]
  jailprev:
    description: Previous page of list.
    usage: |
           /<command>
  jprev:
    description: Previous page of list. Alias to jailprev.
    usage: |
           /<command>
  jailnext:
    description: Next page of list.
    usage: |
           /<command>
  jnext:
    description: Next page of list. Alias to jailnext.
    usage: |
           /<command>
  jailmute:
    description: Mute a player in jail.
    usage: |
           /<command> <player> [player2] ...
  jmute:
    description: Mute a player in jail. Alias to jailmute.
    usage: |
           /<command> <player> [player2] ...
  jailtime:
    description: Give a jailed player a timed release.
    usage: |
           /<command> <player> [player2] ... <time>
  jtime:
    description: Give a jailed player a timed release. Alias to jailtime.
    usage: |
           /<command> <player> [player2] ... <time>
  jailreason:
    description: Sets reason on a player.
    usage: |
           /<command> <player> [reason]
  jreason:
    description: Sets reason on a player. Alias to jailreason.
    usage: |
           /<command> <player> [reason]
  jlast:
    description: Warps to last location of jailed player. Alias to jaillast.
    usage: |
           /<command> <player>
  jaillast:
    description: Warps to last location of jailed player. 
    usage: |
           /<command> <player>
  jinv:
    description: View inventory of jailed player. Alias to jailinv.
    usage: |
           /<command> <player>
  jailinv:
    description: View inventory of jailed player. 
    usage: |
           /<command> <player>
  jwarp:
    description: Warps to jail. Alias to jailwarp.
    usage: |
           /<command> [player]
  jailwarp:
    description: Warps to jail. 
    usage: |
           /<command> [player]
  jhistory:
    description: Player jail history. Alias to jailhistory.
    usage: |
           /<command> [player]
  jailhistory:
    description: Player jail history
    usage: |
           /<command> <args>...
  jailversion:
    description: Get plugin version and config info.
    usage: |
           /<command>
  jversion:
    description: Get plugin version and config info. Alias to jailversion.
    usage: |
           /<command>
  jailreload:
    description: Reload plugin config.
    usage: |
           /<command>
  jreload:
    description: Reload plugin config. Alias to jailreload.
    usage: |
           /<command>

permissions:
  KarmicJail.jail:
    description: Ability to jail players.
    default: op
  KarmicJail.timed:
    description: Ability to jail players.
    default: op
  KarmicJail.unjail:
    description: Ability to unjail players.
    default: op
  KarmicJail.setjail:
    description: Ability to set jail warp points.
    default: op
  KarmicJail.list:
    description: List players in jail
    default: op
  KarmicJail.mute:
    description: Mute players in jail
    default: op
  KarmicJail.inventory.view:
    description: View inventory of jailed players
    default: op
  KarmicJail.inventory.modify:
    description: View inventory of jailed players
    default: op
  KarmicJail.warp.joinignore:
    description: Ignore jail warp on join, if enabled.
    default: op
  KarmicJail.warp.jail:
    description: Warp to jail
    default: op
  KarmicJail.warp.last:
    description: Warp to last location
    default: op
  KarmicJail.history.view:
    description: View jail history
    default: op
  KarmicJail.history.add:
    description: Add comment to jail history
    default: op
  KarmicJail.jailstatus:
    description: Gives access to the jailtime command.
    default: true
  KarmicJail.broadcast:
    description: Allows player to receive the broadcast messages
    default: false
  KarmicJail.exempt:
    description: Exmpts player from being jailed.
    default: op
  KarmicJail.*:
    description: Gives access to all KarmicJail commands.
    children:
      KarmicJail.jail: true
      KarmicJail.timed: true
      KarmicJail.unjail: true
      KarmicJail.setjail: true
      KarmicJail.jailstatus: true
      KarmicJail.list: true
      KarmicJail.mute: true
      KarmicJail.broadcast: true
      KarmicJail.warp.jail: true
      KarmicJail.warp.joinignore: true
      KarmicJail.warp.last: true
      KarmicJail.inventory.view: true
      KarmicJail.inventory.modify: true
      KarmicJail.history.view: true
      KarmicJail.history.add: true
      KarmicJail.exempt: true