name: ${project.artifactId}
description: ${project.description}
main: ${project.mainclass}
version: ${project.version}
author: Original - imjake9 ... Fork - Mitsugaru
depend: [Vault, SQLibrary]
softdepend: [Multiverse-Core]

commands:
  kj:
    description: Root command.

permissions:
  KarmicJail.jail:
    description: Ability to jail players.
    default: op
  KarmicJail.timed:
    description: Ability to jail players.
    default: op
  KarmicJail.unjail:
    description: Ability to unjail players.
    default: op
  KarmicJail.setjail:
    description: Ability to set jail warp points.
    default: op
  KarmicJail.list:
    description: List players in jail
    default: op
  KarmicJail.mute:
    description: Mute players in jail
    default: op
  KarmicJail.inventory.view:
    description: View inventory of jailed players
    default: op
  KarmicJail.inventory.modify:
    description: View inventory of jailed players
    default: op
  KarmicJail.warp.joinignore:
    description: Ignore jail warp on join, if enabled.
    default: op
  KarmicJail.warp.jail:
    description: Warp to jail
    default: op
  KarmicJail.warp.last:
    description: Warp to last location
    default: op
  KarmicJail.history.view:
    description: View jail history
    default: op
  KarmicJail.history.add:
    description: Add comment to jail history
    default: op
  KarmicJail.jailstatus:
    description: Gives access to the jailtime command.
    default: true
  KarmicJail.broadcast:
    description: Allows player to receive the broadcast messages
    default: false
  KarmicJail.exempt:
    description: Exmpts player from being jailed.
    default: op
  KarmicJail.*:
    description: Gives access to all KarmicJail commands.
    children:
      KarmicJail.jail: true
      KarmicJail.timed: true
      KarmicJail.unjail: true
      KarmicJail.setjail: true
      KarmicJail.jailstatus: true
      KarmicJail.list: true
      KarmicJail.mute: true
      KarmicJail.broadcast: true
      KarmicJail.warp.jail: true
      KarmicJail.warp.joinignore: true
      KarmicJail.warp.last: true
      KarmicJail.inventory.view: true
      KarmicJail.inventory.modify: true
      KarmicJail.history.view: true
      KarmicJail.history.add: true
      KarmicJail.exempt: true