name: KarmicJail
main: com.mitsugaru.karmicjail.KarmicJail
description: Jail plugin for Mine-RP
version: 0.32
author: Original - imjake9 ... Fork - Mitsugaru
depend: [Vault]

commands:
  jail:
    description: Places a player in Jail.
    usage: |
           /<command> <player> [player2] ... [time] [reason]
  j:
    description: Places a player in Jail. Alias to jail.
    usage: |
           /<command> <player> [player2] ... [time] [reason]
  unjail:
    description: Removes a player from Jail.
    usage: |
           /<command> <player>
  setjail:
    description: Sets the Jail point.
    usage: |
           /<command>
           /<command> <x> <y> <z> <world>
  setunjail:
    description: Sets the Jail removal point.
    usage: |
           /<command>
           /<command> <x> <y> <z> <world>
  jailstatus:
    description: Checks remaining tempjail time.
    usage: |
           /<command>
           /<command> <player>
  jstatus:
    description: Checks remaining tempjail time. Alias to jailstatus.
    usage: |
           /<command>
           /<command> <player>
  jailhelp:
    description: Jail help.
    usage: |
           /<command>
  jhelp:
    description: Jail help. Alias to jailhelp.
    usage: |
           /<command>
  jaillist:
    description: List jailed players.
    usage: |
           /<command> [page]
  jlist:
    description: List jailed players. Alias to jaillist.
    usage: |
           /<command> [page]
  jailprev:
    description: Previous page of list.
    usage: |
           /<command>
  jprev:
    description: Previous page of list. Alias to jailprev.
    usage: |
           /<command>
  jailnext:
    description: Next page of list.
    usage: |
           /<command>
  jnext:
    description: Next page of list. Alias to jailnext.
    usage: |
           /<command>
  jailmute:
    description: Mute a player in jail.
    usage: |
           /<command> <player> [player2] ...
  jmute:
    description: Mute a player in jail. Alias to jailmute.
    usage: |
           /<command> <player> [player2] ...
  jailtime:
    description: Give a jailed player a timed release.
    usage: |
           /<command> <player> [player2] ... <time>
  jtime:
    description: Give a jailed player a timed release. Alias to jailtime.
    usage: |
           /<command> <player> [player2] ... <time>
  jailreason:
    description: Sets reason on a player.
    usage: |
           /<command> <player> [reason]
  jreason:
    description: Sets reason on a player. Alias to jailreason.
    usage: |
           /<command> <player> [reason]
  jailversion:
    description: Get plugin version and config info.
    usage: |
           /<command>
  jversion:
    description: Get plugin version and config info. Alias to jailversion.
    usage: |
           /<command>
  jailreload:
    description: Reload plugin config.
    usage: |
           /<command>
  jreload:
    description: Reload plugin config. Alias to jailreload.
    usage: |
           /<command>

permissions:
  KarmicJail.jail:
    description: Ability to jail players.
    default: op
  KarmicJail.unjail:
    description: Ability to unjail players.
    default: op
  KarmicJail.setjail:
    description: Ability to set jail warp points.
    default: op
  KarmicJail.list:
    description: List players in jail
    default: op
  KarmicJail.mute:
    description: Mute players in jail
    default: op
  KarmicJail.jailstatus:
    description: Gives access to the jailtime command.
    default: true
  KarmicJail.*:
    description: Gives access to all KarmicJail commands.
    children:
      KarmicJail.jail: true
      KarmicJail.unjail: true
      KarmicJail.setjail: true
      KarmicJail.jailstatus: true
      KarmicJail.list: true
      KarmicJail.mute: true